busybox-initramfs: added rpi usb auto update support and ads nfs and cifs auto update support. fixes #1653 and fixes #1691 closes #1838

diff --git a/packages/initramfs/sysutils/busybox-initramfs/scripts/init b/packages/initramfs/sysutils/busybox-initramfs/scripts/init
--- a/packages/initramfs/sysutils/busybox-initramfs/scripts/init
+++ b/packages/initramfs/sysutils/busybox-initramfs/scripts/init
@@ -42,6 +42,9 @@
   MD5_NOCHECK="0"
   SIZE_FAILED="0"
 
+  # iotimeout for media_check, disabled by default. typical value 5000.
+  IO_TIMEOUT=0
+
   NBD_DEVS="0"
   FLASH_FREE_MIN="5"
   LIVE_FLASH_FREE_MIN="50"
@@ -50,9 +53,7 @@
   SYSTEM_TORAM_LIMIT=1024000
 
 # load any configuration
-  if [ -f "/etc/initramfs.conf" ]; then
-    . /etc/initramfs.conf
-  fi
+  [ -f "/etc/initramfs.conf" ] && . /etc/initramfs.conf
 
 # hide kernel log messages on console
   echo '1 4 1 7' > /proc/sys/kernel/printk
@@ -60,6 +61,9 @@
 # clear screen and hide cursor
   /bin/busybox clear
   echo 0 > /sys/devices/virtual/graphics/fbcon/cursor_blink
+
+# is current device a Raspberry Pi?
+  [ -n "$(/bin/busybox cat /proc/cpuinfo | /bin/busybox grep -E "Hardware.*:.*BCM2708")" ] && IS_RPI=Y
 
 # parse command line arguments
   for arg in $(cat /proc/cmdline); do
@@ -72,9 +76,19 @@
         ;;
       boot=*)
         boot="${arg#*=}"
+        # BOOT_TYPE: local, nfs, nbd, iscsi, cifs etc.
+        BOOT_TYPE="$(echo "${boot}" | /bin/busybox sed -r "s/(.*)=.*/\1/" | /bin/busybox tr '[A-Z]' '[a-z]')"
+        [ -n "$(echo "${BOOT_TYPE}" | /bin/busybox grep -E "^/|^label|^uuid")" ] && BOOT_TYPE="local"
+        # Booting a Raspberry Pi from direct attached media, but not from SD card... so USB
+        [ "${IS_RPI}" = "Y" -a "${BOOT_TYPE}" = "local" -a "${boot}" != "/dev/mmcblk0p1" ] && BOOT_TYPE="usb"
+        BOOT_OPTIONS="$(echo "${boot}" | /bin/busybox sed -r "s/.*=(.*)/\1/")"
         ;;
       disk=*)
         disk="${arg#*=}"
+        # DISK_TYPE: local, nfs, nbd, iscsi, cifs etc.
+        DISK_TYPE="$(echo "${disk}" | /bin/busybox sed -r "s/(.*)=.*/\1/" | /bin/busybox tr '[A-Z]' '[a-z]')"
+        [ -n "$(echo "${DISK_TYPE}" | /bin/busybox grep -E "^/|^label|^uuid")" ] && DISK_TYPE="local"
+        DISK_OPTIONS="$(echo "${disk}" | /bin/busybox sed -r "s/.*=(.*)/\1/")"
         ;;
       debugging)
         DEBUG=yes
@@ -94,6 +108,9 @@
       noram)
         SYSTEM_TORAM=no
         ;;
+      iotimeout=*)
+        IO_TIMEOUT="${arg#*=}"
+        ;;
       overlay)
         OVERLAY=yes
         ;;
@@ -111,9 +128,7 @@
   SILENT_OUT=3
 
   progress() {
-    if test "$PROGRESS" = "yes"; then
-      echo "### $1 ###"
-    fi
+    [ "$PROGRESS" = "yes" ] && echo "### $1 ###"
   }
 
   debug_shell() {
@@ -143,6 +158,18 @@
         debug_shell
         ;;
     esac
+  }
+
+  countdown() {
+    MESSAGE="$1"
+    COUNT=${2:-10}
+    while [ $COUNT -ge 0 ]; do
+      [ $COUNT -eq 1 ] && S="" || S="s"
+      echo -ne "${MESSAGE} \033[1;36m$COUNT second${S}\033[m\017...    \r"
+      COUNT=$((${COUNT}-1))
+      /bin/busybox usleep 1000000
+    done
+    echo
   }
 
   # Mount handlers
@@ -297,29 +324,37 @@
     $MOUNT_CMD "$MOUNT_TARGET" "$2" "$3" "$4"
   }
 
+  mount_remount() {
+  # Remount mount point ($1) with new rw/ro mode ($2) only when required.
+    NEW_MODE="$2"
+    if [ -z "$(/bin/busybox grep " $1 " /proc/mounts | /bin/busybox awk -v MODE="$NEW_MODE" '$4~"(^|,)"MODE"($|,)"')" ]; then
+       /bin/busybox sync
+       /bin/busybox mount -o remount,$NEW_MODE /$1
+    fi
+  }
+
   update() {
-    if [ -f "$UPDATE_DIR/$2" -a -f "$3" ]; then
-      echo "updating $1..."
-        /bin/busybox mount -o remount,rw /flash
-        /bin/busybox mv $UPDATE_DIR/$2 $3
-        # loopback file needs writable /flash all the time
-        if [ "${disk%%=*}" != "FILE" ]; then
-          /bin/busybox mount -o remount,ro /flash
-        fi
-        /bin/busybox sync
+    if [ -f "$UPDATE_DIR/$2" -a -f "$3/$4" ]; then
+      [ "$3" = "/flash" ] && TARGET=$BOOT_TYPE || TARGET="local"
+      echo "Updating $1 on $TARGET..."
+      mount_remount "$3" "rw"
+      /bin/busybox mv $UPDATE_DIR/$2 $3/$4
+      /bin/busybox sync
+      mount_remount "$3" "ro"
     fi
   }
 
   update_bootloader() {
     if [ -f "/flash/$IMAGE_SYSTEM" ]; then
-    # /flash is filesystem with system image file
-      export BOOT_ROOT="/flash"
+    # /flash is normally filesystem with system image file
+      export BOOT_ROOT="$1"
       export SYSTEM_ROOT="/sysroot"
 
       mount_part "/flash/$IMAGE_SYSTEM" "/sysroot" "ro,loop"
 
       if [ -f $SYSTEM_ROOT/usr/share/bootloader/update.sh ]; then
-        echo "updating Bootloader..."
+        [ "$1" = "/flash" ] && TARGET=$BOOT_TYPE || TARGET="local"
+        echo "Updating Bootloader on $TARGET..."
           /bin/busybox sh $SYSTEM_ROOT/usr/share/bootloader/update.sh
           /bin/busybox sync
       fi
@@ -338,7 +373,7 @@
         esac
       done
 
-      if [ "$FS_TYPE" = "\"hfs\"" -o "$FS_TYPE" = "\"hfsplus\"" ]; then
+      if [ "$FS_TYPE" = '"hfs"' -o "$FS_TYPE" = '"hfsplus"' ]; then
         progress "check filesystem $DEVICE [$FS_TYPE]..."
         /bin/fsck_hfs -r -y $DEVICE >&$SILENT_OUT 2>&1
       fi
@@ -478,6 +513,75 @@
     fi
   }
 
+  media_check() {
+    if [ "$IO_TIMEOUT" -gt "0" ]; then
+      progress "Media integrity check"
+
+      [ "$IS_RPI" = "Y" ] && media_check_rpi
+    fi
+  }
+
+#
+# Determine how long it takes to write libc.so.6 (~1.2MB) to the
+# Raspberry Pi SD memory card. This IO operation should complete in
+# under 5 seconds - any longer and the SD card is likely to end
+# up with corrupted boot files and/or secondary partition.
+#
+# To avoid this corruption, system will reboot and check again.
+#
+# Enable media_check by setting iotimeout > 0, eg. 5000.
+#
+  media_check_rpi() {
+
+    # Show the following message which will appear momentarily when there
+    # is no problem, but remain visible for entire duration of slow I/O
+    # operation when there is a performance issue.
+    echo "Media check - please wait..."
+
+    # any decent sized (>512KB) file will do
+    SOURCE="/lib/libc.so.6"
+
+    # Get current time in miliseconds (discard remaining digits)
+    IO_START=$(/bin/busybox grep "now at [0-9]* nsecs" /proc/timer_list | /bin/busybox sed -e "s/now at \(.*\)[0-9][0-9][0-9][0-9][0-9][0-9] nsecs/\1/")
+
+    if [ "$BOOT_TYPE" = "local" ] ; then
+      mount_remount "/flash" "rw"
+      /bin/busybox cp "$SOURCE" "/flash/.openelec" 2>/dev/null
+      CP_RES=$?
+      /bin/busybox sync
+      [ -f "/flash/.openelec" ] && ( /bin/busybox rm "/flash/.openelec" && /bin/busybox sync )
+      mount_remount "/flash" "ro"
+     else
+      /bin/busybox mkdir /bootroot && mount_part "/dev/mmcblk0p1" "/bootroot" "rw,noatime"
+      /bin/busybox cp "$SOURCE" "/bootroot/.openelec" 2>/dev/null
+      CP_RES=$?
+      /bin/busybox sync
+      [ -f "/bootroot/.openelec" ] && ( /bin/busybox rm "/bootroot/.openelec" && /bin/busybox sync )
+      /bin/busybox umount /bootroot && /bin/busybox rm -fr /bootroot
+    fi
+
+    IO_END=$(/bin/busybox grep "now at [0-9]* nsecs" /proc/timer_list | /bin/busybox sed -e "s/now at \(.*\)[0-9][0-9][0-9][0-9][0-9][0-9] nsecs/\1/")
+    IO_TIME=$((${IO_END}-${IO_START}))
+
+    progress "media_check: i/o time [$IO_TIME], timeout [$IO_TIMEOUT]"
+
+    if [ $IO_TIME -gt $IO_TIMEOUT -o $CP_RES -ne 0 ]; then
+      if [ $CP_RES -eq 0 ]; then
+        echo "media_check: Write I/O interval ${IO_TIME}ms has exceeded iotimeout ${IO_TIMEOUT}ms"
+      else
+        echo "media_check: Write I/O failed, most likely due to mount point failure"
+      fi
+      echo "media_check: SD Card performance is low."
+      countdown "media_check: Rebooting to improve performance in" 10
+      /bin/busybox reboot
+    fi
+
+    # Use ESC M (reverse linefeed) to remove previous "Please wait"
+    # message, leaving cursor on same line (top line of screen) ready
+    # for version/build number.
+    [ "$PROGRESS" != "yes" ] && echo -ne "\033M                            \r"
+  }
+
   check_update() {
     progress "Checking for updates"
 
@@ -507,6 +611,7 @@
       fi
 
       # get sizes
+      # TODO: Get size from USB NFS and CIFS... ?? How...
       FLASH_FREE=$(/bin/busybox df /flash/ | awk '/[0-9]%/{print $4}')
       FLASH_FREE=$(( $FLASH_FREE * 1024 ))
       OLD_KERNEL=$(/bin/busybox stat -t "/flash/$IMAGE_KERNEL" | awk '{print $2}')
@@ -531,15 +636,31 @@
       if [ "$SIZE_FAILED" -eq "0" ] ; then
         # update if md5 check is ok or .nocheck exists
         if [ "$MD5_FAILED" -eq "0" -o "$MD5_NOCHECK" -eq "1" ] ; then
-          update "Kernel" "$UPDATE_KERNEL" "/flash/$IMAGE_KERNEL"
-          update "System" "$UPDATE_SYSTEM" "/flash/$IMAGE_SYSTEM"
-          update_bootloader
+          if [ "$BOOT_TYPE" = "local" ] ; then
+            update "Kernel" "$UPDATE_KERNEL" "/flash" "$IMAGE_KERNEL"
+            update "System" "$UPDATE_SYSTEM" "/flash" "$IMAGE_SYSTEM"
+            update_bootloader "/flash"
+            REBOOT="1"
+          else
+            # Booted from remote fs, need mountpoint for boot media
+            # in order to update kernel and any associated boot files
+            /bin/busybox mkdir /bootroot
+
+            #TODO: Where does PXE mount device with kernel?
+            # Need sane alternative solution for non-RPi devices in order to update kernel.img
+            [ "${IS_RPI}" = "Y" ] && mount_part "/dev/mmcblk0p1" "/bootroot" "rw,noatime"
+
+            update "Kernel" "$UPDATE_KERNEL" "/bootroot" "$IMAGE_KERNEL"
+            update "System" "$UPDATE_SYSTEM" "/flash" "$IMAGE_SYSTEM"
+            update_bootloader "/bootroot"
+
+            /bin/busybox umount /bootroot && /bin/busybox rm -fr /bootroot
+          fi
           REBOOT="1"
         else
           /bin/busybox rm -rf $UPDATE_DIR/[0-9a-zA-Z]* &>/dev/null
-          echo "md5 check failed. normal startup in 30s..."
           /bin/busybox sync
-          /bin/busybox usleep 30000000
+          countdown "md5 check failed. normal startup in" 30
         fi
         /bin/busybox rm -rf $UPDATE_DIR/[0-9a-zA-Z]* &>/dev/null
       else
@@ -550,9 +671,8 @@
       fi
     fi
 
-    if test "$REBOOT" -eq "1"; then
-      echo "System reboots now..."
-      /bin/busybox usleep 2000000
+    if [ "$REBOOT" -eq "1" ]; then
+      countdown "System rebooting in" 5
       /bin/busybox reboot
     fi
   }
@@ -565,6 +685,7 @@
       if [ "$SYSTEM_TORAM" = "no" -o "$INSTALLED_MEMORY" -lt "$SYSTEM_TORAM_LIMIT" ]; then
         mount_part "/flash/$IMAGE_SYSTEM" "/sysroot" "ro,loop"
       else
+        progress "Loading System to RAM"
         cp /flash/$IMAGE_SYSTEM /dev/$IMAGE_SYSTEM
         mount_part "/dev/$IMAGE_SYSTEM" "/sysroot" "ro,loop"
       fi
@@ -592,6 +713,7 @@
       check_disks \
       mount_flash \
       load_splash \
+      media_check \
       mount_storage \
       check_update \
       prepare_sysroot; do
