Verify downloaded sources against a SHA256 checksum.
Sources were previously downloaded over HTTP and FTP then built without
validating their integrity. This is dangerous not only because the final build
may be manipulated by an attacker but also because during the build an attacker
could gain arbitary code execution during the configuration stage of most
packages on the machine doing the build.

In addition to increased security, this prevents package maintainers modifying
sources without bumping package numbers which could cause confusing bugs.

Checksums are stored in package.mk files in the variable $PKG_SHA256. I have
provided initial checksums for all packages which require it (excluding virtual
packages). Checksums can be automatically updated by running `$ make checksums`.
Which modifies in place all package.mk files, downloading files as appropriate.
New packages must have the PKG_SHA256 variable declared. A person adding a new
package may then use the `$ make checksums` command to fill it in automatically.

diff --git a/scripts/get b/scripts/get
--- a/scripts/get
+++ b/scripts/get
@@ -20,7 +20,13 @@
 
 . config/options $1
 
-if [ -z "$1" ]; then
+if [ "$1" = "--update-checksums" ]; then
+  export UPDATE_CHECKSUMS=true
+fi
+if [ -z "$1" ] || [ "$1" = "--update-checksums" ]; then
+  if [ "$1" = "--update-checksums" ]; then
+    export UPDATE_CHECKSUMS=true
+  fi
   for i in `find packages/ -type f -name package.mk`; do
     GET_PKG=`grep ^PKG_NAME= $i | sed -e "s,\",,g" -e "s,PKG_NAME=,,"`
     $SCRIPTS/get $GET_PKG
@@ -61,6 +67,23 @@ if [ -n "$PKG_URL" ]; then
         exit 1
       fi
     done
+
+    if [ "$UPDATE_CHECKSUMS" = true ]; then
+      sum="$(sha256sum $PACKAGE | awk '{print $1}')"
+      tmp=$(mktemp)
+      awk -F= '
+        BEGIN{
+          OFS="="
+        }
+        $1 == "PKG_SHA256"{
+          $2="\"'"$sum"'\""
+        }
+        {print}' "$PKG_DIR/package.mk" > $tmp
+      mv $tmp "$PKG_DIR/package.mk"
+    elif ! sha256sum --strict --status --check <<< "$PKG_SHA256 $PACKAGE"; then
+      echo "Package integrity check failed."
+      exit 1
+    fi
 
     echo $i > $STAMP
     md5sum -t $PACKAGE > $MD5SUM
